languageCode = 'en-us'
title = 'Blog - Capital Parking Lot Lines Painting (CPLS)'
theme = 'ananke'
googleAnalytics = "G-VRFCW41NVK"
[services]
  [services.googleAnalytics]
    ID = 'G-VRFCW41NVK'
[ananke_socials]
    name = "linkedin"
    url = "https://www.linkedin.com/"
    label = "My Linkedin"
